In [126]:
import pandas as pd
import numpy as np

In [127]:
pd.set_option('display.max_rows', 500)

In [128]:
gompertz = pd.read_csv('CovidColombia.csv', low_memory=False, usecols= ['ID de caso', 'Fecha de notificación', 
                                                                        'Ciudad de ubicación', 
                                                                        'Departamento o Distrito '], 
                                                                        parse_dates=['Fecha de notificación'] )

In [129]:
gompertz.sort_values(by=['Fecha de notificación'],inplace=True)

In [130]:
df = pd.DataFrame(gompertz['Fecha de notificación']).loc[0]

In [131]:
a = gompertz.loc[0,'Fecha de notificación']

In [132]:
b = np.datetime64('today') 
b

numpy.datetime64('2020-07-24')

In [133]:
longitud = (b-a)/ np.timedelta64(1, 'D')
longitud=int(longitud)-1
longitud

143

In [134]:
df_fechas = pd.DataFrame(df).transpose()
df_fechas

  Fecha de notificación
0            2020-03-02

In [135]:
df_fechas['ID de caso']=0

In [136]:
df_fechas

  Fecha de notificación  ID de caso
0            2020-03-02           0

In [137]:
pd.to_datetime([df_fechas.loc[0,'Fecha de notificación']])

DatetimeIndex(['2020-03-02'], dtype='datetime64[ns]', freq=None)

In [138]:
(np.datetime64(df_fechas.loc[0, 'Fecha de notificación']) + np.timedelta64(1,'D'))

numpy.datetime64('2020-03-03T00:00:00.000000')

In [139]:
for i in range(1,longitud):
    df_fechas.loc[(i)] = [(np.datetime64(df_fechas.loc[i-1, 'Fecha de notificación']) + np.timedelta64(1,'D')),0]

In [140]:
df_fechas

    Fecha de notificación  ID de caso
0              2020-03-02           0
1              2020-03-03           0
2              2020-03-04           0
3              2020-03-05           0
4              2020-03-06           0
5              2020-03-07           0
6              2020-03-08           0
7              2020-03-09           0
8              2020-03-10           0
9              2020-03-11           0
10             2020-03-12           0
11             2020-03-13           0
12             2020-03-14           0
13             2020-03-15           0
14             2020-03-16           0
15             2020-03-17           0
16             2020-03-18           0
17             2020-03-19           0
18             2020-03-20           0
19             2020-03-21           0
20             2020-03-22           0
21             2020-03-23           0
22             2020-03-24           0
23             2020-03-25           0
24             2020-03-26           0
25             2020-03-27           0
26             2020-03-28           0
27             2020-03-29           0
28             2020-03-30           0
29             2020-03-31           0
30             2020-04-01           0
31             2020-04-02           0
32             2020-04-03           0
33             2020-04-04           0
34             2020-04-05           0
35             2020-04-06           0
36             2020-04-07           0
37             2020-04-08           0
38             2020-04-09           0
39             2020-04-10           0
40             2020-04-11           0
41             2020-04-12           0
42             2020-04-13           0
43             2020-04-14           0
44             2020-04-15           0
45             2020-04-16           0
46             2020-04-17           0
47             2020-04-18           0
48             2020-04-19           0
49             2020-04-20           0
50             2020-04-21           0
51             2020-04-22           0
52             2020-04-23           0
53             2020-04-24           0
54             2020-04-25           0
55             2020-04-26           0
56             2020-04-27           0
57             2020-04-28           0
58             2020-04-29           0
59             2020-04-30           0
60             2020-05-01           0
61             2020-05-02           0
62             2020-05-03           0
63             2020-05-04           0
64             2020-05-05           0
65             2020-05-06           0
66             2020-05-07           0
67             2020-05-08           0
68             2020-05-09           0
69             2020-05-10           0
70             2020-05-11           0
71             2020-05-12           0
72             2020-05-13           0
73             2020-05-14           0
74             2020-05-15           0
75             2020-05-16           0
76             2020-05-17           0
77             2020-05-18           0
78             2020-05-19           0
79             2020-05-20           0
80             2020-05-21           0
81             2020-05-22           0
82             2020-05-23           0
83             2020-05-24           0
84             2020-05-25           0
85             2020-05-26           0
86             2020-05-27           0
87             2020-05-28           0
88             2020-05-29           0
89             2020-05-30           0
90             2020-05-31           0
91             2020-06-01           0
92             2020-06-02           0
93             2020-06-03           0
94             2020-06-04           0
95             2020-06-05           0
96             2020-06-06           0
97             2020-06-07           0
98             2020-06-08           0
99             2020-06-09           0
100            2020-06-10           0
101            2020-06-11           0
102            2020-06-12           0
103            2020-06-13           0
104            2020-06-14           0
105            2020-06-15           0
106            2020-06-16           0
107            2020-06-17           0
108            2020-06-18           0
109            2020-06-19           0
110            2020-06-20           0
111            2020-06-21           0
112            2020-06-22           0
113            2020-06-23           0
114            2020-06-24           0
115            2020-06-25           0
116            2020-06-26           0
117            2020-06-27           0
118            2020-06-28           0
119            2020-06-29           0
120            2020-06-30           0
121            2020-07-01           0
122            2020-07-02           0
123            2020-07-03           0
124            2020-07-04           0
125            2020-07-05           0
126            2020-07-06           0
127            2020-07-07           0
128            2020-07-08           0
129            2020-07-09           0
130            2020-07-10           0
131            2020-07-11           0
132            2020-07-12           0
133            2020-07-13           0
134            2020-07-14           0
135            2020-07-15           0
136            2020-07-16           0
137            2020-07-17           0
138            2020-07-18           0
139            2020-07-19           0
140            2020-07-20           0
141            2020-07-21           0
142            2020-07-22           0

In [141]:

gompertz

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,2,2020-03-06,Guadalajara de Buga,Valle del Cauca
2,3,2020-03-07,Medellín,Antioquia
6,7,2020-03-08,Cartagena de Indias,Cartagena D.T. y C.
8,9,2020-03-08,Bogotá D.C.,Bogotá D.C.
...,...,...,...,...
225480,225521,2020-07-22,Medellín,Antioquia
225470,225511,2020-07-22,Medellín,Antioquia
225582,225623,2020-07-22,Pasto,Nariño
225919,225960,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.
225782,225823,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.

In [146]:
gompertz_final=gompertz.append(df_fechas).sort_values(by=['Fecha de notificación'], ignore_index=True)

In [147]:
gompertz_final

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
226511,225757,2020-07-22,Sabaneta,Antioquia
226512,225754,2020-07-22,Buriticá,Antioquia
226513,225624,2020-07-22,Pasto,Nariño
226514,225823,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.
226515,225960,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.

In [149]:
longitud1 = gompertz_final['ID de caso'].size
longitud1

226516

In [150]:
gompertz_final.columns

Index(['ID de caso', 'Fecha de notificación', 'Ciudad de ubicación',
       'Departamento o Distrito '],
      dtype='object')

In [151]:
for i in range(0, longitud1):
    if gompertz_final.loc[i, 'ID de caso'] == 0:
        pass
    else:
        gompertz_final.loc[i, 'ID de caso'] = 1

In [152]:
gompertz_final

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
226511,1,2020-07-22,Sabaneta,Antioquia
226512,1,2020-07-22,Buriticá,Antioquia
226513,1,2020-07-22,Pasto,Nariño
226514,1,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.
226515,1,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.

In [153]:
gompertz_final['Acumulados']= 0
gompertz_final['Día número']=0
gompertz_final['Penetración real']=0
gompertz_final

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,0,0,0
1,0,2020-03-02,NaN,NaN,0,0,0
2,0,2020-03-03,NaN,NaN,0,0,0
3,0,2020-03-04,NaN,NaN,0,0,0
4,0,2020-03-05,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...
226511,1,2020-07-22,Sabaneta,Antioquia,0,0,0
226512,1,2020-07-22,Buriticá,Antioquia,0,0,0
226513,1,2020-07-22,Pasto,Nariño,0,0,0
226514,1,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.,0,0,0
226515,1,2020-07-23,Cartagena de Indias,Cartagena D.T. y C.,0,0,0

In [154]:
gompertz_final.index

RangeIndex(start=0, stop=226516, step=1)

In [ ]:
longitud2 = trabajo['Casos Notificados diarios'].size
longitud2

In [ ]:
trabajo.loc[0, 'Acumulados']= trabajo.loc[0, 'Casos Notificados diarios']
for i in range(1, longitud2):
    trabajo.loc[i,'Acumulados'] = trabajo.loc[i, 'Casos Notificados diarios'] + trabajo.loc[i-1, 'Acumulados']

In [ ]:
trabajo

In [ ]:
trabajo.loc[longitud2-1, 'Acumulados']

In [ ]:
trabajo.loc[0, 'Día número'] = 1
for i in range(1, longitud2):
    trabajo.loc[i,'Penetración real'] = trabajo.loc[i, 'Acumulados']/ trabajo.loc[longitud2-1, 'Acumulados']
    trabajo.loc[i,'Día número'] = i+1

In [ ]:
trabajo

In [ ]:
#trabajo.to_excel('datosTotalesparaGompertz1.xlsx')
trabajo.to_excel('datosTotalesparaGompertzDpto1.xlsx')
#trabajo.to_excel('datosTotalesparaGompertzCiudad1.xlsx')