In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 1000)

In [3]:
gompertz = pd.read_csv('CovidColombia.csv', low_memory=False, usecols= ['ID de caso', 'Fecha de notificación', 
                                                                        'Ciudad de ubicación', 
                                                                        'Departamento o Distrito '], 
                                                                        parse_dates=['Fecha de notificación'] )

In [4]:
gompertz.sort_values(by=['Fecha de notificación'],inplace=True)

In [5]:
gompertz.columns

Index(['ID de caso', 'Fecha de notificación', 'Ciudad de ubicación',
       'Departamento o Distrito '],
      dtype='object')

In [6]:
gompertz['Fecha de notificación']= gompertz['Fecha de notificación'].dt.floor('d')

In [7]:
gompertz

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,2,2020-03-06,Guadalajara de Buga,Valle del Cauca
2,3,2020-03-07,Medellín,Antioquia
6,7,2020-03-08,Cartagena de Indias,Cartagena D.T. y C.
8,9,2020-03-08,Bogotá D.C.,Bogotá D.C.
...,...,...,...,...
332518,332559,2020-08-04,Barranquilla,Barranquilla D.E.
330864,330905,2020-08-04,Barranquilla,Barranquilla D.E.
332572,332613,2020-08-04,Barranquilla,Barranquilla D.E.
332424,332465,2020-08-04,Barranquilla,Barranquilla D.E.
332453,332494,2020-08-04,Neiva,Huila

In [8]:
gompertz.loc[237959,'Fecha de notificación']

Timestamp('2020-07-18 00:00:00')

In [9]:
df = pd.DataFrame(gompertz['Fecha de notificación']).loc[0]
df

Fecha de notificación   2020-03-02
Name: 0, dtype: datetime64[ns]

In [10]:
a = gompertz.loc[0,'Fecha de notificación']

In [11]:
b = np.datetime64('today') 
b

numpy.datetime64('2020-08-05')

In [12]:
longitud = (b-a)/ np.timedelta64(1, 'D')
longitud=int(longitud)-1
longitud

155

In [13]:
df_fechas = pd.DataFrame(df).transpose()
df_fechas

  Fecha de notificación
0            2020-03-02

In [14]:
df_fechas['ID de caso']=0

In [15]:
df_fechas

  Fecha de notificación  ID de caso
0            2020-03-02           0

In [16]:
pd.to_datetime([df_fechas.loc[0,'Fecha de notificación']])

DatetimeIndex(['2020-03-02'], dtype='datetime64[ns]', freq=None)

In [17]:
(np.datetime64(df_fechas.loc[0, 'Fecha de notificación']) + np.timedelta64(1,'D'))

numpy.datetime64('2020-03-03T00:00:00.000000')

In [18]:
for i in range(1,longitud):
    df_fechas.loc[(i)] = [(np.datetime64(df_fechas.loc[i-1, 'Fecha de notificación']) + np.timedelta64(1,'D')),0]

In [19]:
df_fechas

    Fecha de notificación  ID de caso
0              2020-03-02           0
1              2020-03-03           0
2              2020-03-04           0
3              2020-03-05           0
4              2020-03-06           0
5              2020-03-07           0
6              2020-03-08           0
7              2020-03-09           0
8              2020-03-10           0
9              2020-03-11           0
10             2020-03-12           0
11             2020-03-13           0
12             2020-03-14           0
13             2020-03-15           0
14             2020-03-16           0
15             2020-03-17           0
16             2020-03-18           0
17             2020-03-19           0
18             2020-03-20           0
19             2020-03-21           0
20             2020-03-22           0
21             2020-03-23           0
22             2020-03-24           0
23             2020-03-25           0
24             2020-03-26           0
25             2020-03-27           0
26             2020-03-28           0
27             2020-03-29           0
28             2020-03-30           0
29             2020-03-31           0
30             2020-04-01           0
31             2020-04-02           0
32             2020-04-03           0
33             2020-04-04           0
34             2020-04-05           0
35             2020-04-06           0
36             2020-04-07           0
37             2020-04-08           0
38             2020-04-09           0
39             2020-04-10           0
40             2020-04-11           0
41             2020-04-12           0
42             2020-04-13           0
43             2020-04-14           0
44             2020-04-15           0
45             2020-04-16           0
46             2020-04-17           0
47             2020-04-18           0
48             2020-04-19           0
49             2020-04-20           0
50             2020-04-21           0
51             2020-04-22           0
52             2020-04-23           0
53             2020-04-24           0
54             2020-04-25           0
55             2020-04-26           0
56             2020-04-27           0
57             2020-04-28           0
58             2020-04-29           0
59             2020-04-30           0
60             2020-05-01           0
61             2020-05-02           0
62             2020-05-03           0
63             2020-05-04           0
64             2020-05-05           0
65             2020-05-06           0
66             2020-05-07           0
67             2020-05-08           0
68             2020-05-09           0
69             2020-05-10           0
70             2020-05-11           0
71             2020-05-12           0
72             2020-05-13           0
73             2020-05-14           0
74             2020-05-15           0
75             2020-05-16           0
76             2020-05-17           0
77             2020-05-18           0
78             2020-05-19           0
79             2020-05-20           0
80             2020-05-21           0
81             2020-05-22           0
82             2020-05-23           0
83             2020-05-24           0
84             2020-05-25           0
85             2020-05-26           0
86             2020-05-27           0
87             2020-05-28           0
88             2020-05-29           0
89             2020-05-30           0
90             2020-05-31           0
91             2020-06-01           0
92             2020-06-02           0
93             2020-06-03           0
94             2020-06-04           0
95             2020-06-05           0
96             2020-06-06           0
97             2020-06-07           0
98             2020-06-08           0
99             2020-06-09           0
100            2020-06-10           0
101            2020-06-11           0
102            2020-06-12           0
103            2020-06-13           0
104            2020-06-14           0
105            2020-06-15           0
106            2020-06-16           0
107            2020-06-17           0
108            2020-06-18           0
109            2020-06-19           0
110            2020-06-20           0
111            2020-06-21           0
112            2020-06-22           0
113            2020-06-23           0
114            2020-06-24           0
115            2020-06-25           0
116            2020-06-26           0
117            2020-06-27           0
118            2020-06-28           0
119            2020-06-29           0
120            2020-06-30           0
121            2020-07-01           0
122            2020-07-02           0
123            2020-07-03           0
124            2020-07-04           0
125            2020-07-05           0
126            2020-07-06           0
127            2020-07-07           0
128            2020-07-08           0
129            2020-07-09           0
130            2020-07-10           0
131            2020-07-11           0
132            2020-07-12           0
133            2020-07-13           0
134            2020-07-14           0
135            2020-07-15           0
136            2020-07-16           0
137            2020-07-17           0
138            2020-07-18           0
139            2020-07-19           0
140            2020-07-20           0
141            2020-07-21           0
142            2020-07-22           0
143            2020-07-23           0
144            2020-07-24           0
145            2020-07-25           0
146            2020-07-26           0
147            2020-07-27           0
148            2020-07-28           0
149            2020-07-29           0
150            2020-07-30           0
151            2020-07-31           0
152            2020-08-01           0
153            2020-08-02           0
154            2020-08-03           0

In [20]:
gompertz_Col=gompertz.append(df_fechas).sort_values(by=['Fecha de notificación'], ignore_index=True)

In [21]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
335129,332555,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.
335130,332551,2020-08-04,Bucaramanga,Santander
335131,331277,2020-08-04,Santo Tomás,Atlántico
335132,332507,2020-08-04,Barranquilla,Barranquilla D.E.
335133,332556,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.

In [22]:
longitud = gompertz_Col['ID de caso'].size
longitud

335134

In [23]:
for i in range(0, longitud):
    if gompertz_Col.loc[i, 'ID de caso'] == 0:
        pass
    else:
        gompertz_Col.loc[i, 'ID de caso'] = 1

In [24]:
#pd.to_datetime(gompertz_Col.loc[237958,'Fecha de notificación'], format='%Y-%m-%d')
#gompertz_Col.loc[237958, 'Fecha de notificación']

In [25]:
gompertz_Col['Acumulados']= 0
gompertz_Col['Día número']=0
gompertz_Col['Penetración real']=0
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,0,0,0
1,0,2020-03-02,NaN,NaN,0,0,0
2,0,2020-03-03,NaN,NaN,0,0,0
3,0,2020-03-04,NaN,NaN,0,0,0
4,0,2020-03-05,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...
335129,1,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.,0,0,0
335130,1,2020-08-04,Bucaramanga,Santander,0,0,0
335131,1,2020-08-04,Santo Tomás,Atlántico,0,0,0
335132,1,2020-08-04,Barranquilla,Barranquilla D.E.,0,0,0
335133,1,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.,0,0,0

In [26]:
gompertz_Col.shape

(335134, 7)

In [27]:
gompertz_Col.loc[0, 'Acumulados']= gompertz_Col.loc[0, 'ID de caso']
for i in range(1, longitud):
    gompertz_Col.loc[i,'Acumulados'] = gompertz_Col.loc[i, 'ID de caso'] + gompertz_Col.loc[i-1, 'Acumulados']

In [28]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,1,0,0
1,0,2020-03-02,NaN,NaN,1,0,0
2,0,2020-03-03,NaN,NaN,1,0,0
3,0,2020-03-04,NaN,NaN,1,0,0
4,0,2020-03-05,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...
335129,1,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.,334975,0,0
335130,1,2020-08-04,Bucaramanga,Santander,334976,0,0
335131,1,2020-08-04,Santo Tomás,Atlántico,334977,0,0
335132,1,2020-08-04,Barranquilla,Barranquilla D.E.,334978,0,0
335133,1,2020-08-04,Cartagena de Indias,Cartagena D.T. y C.,334979,0,0

In [29]:
gompertz_Colombia = gompertz_Col.groupby('Fecha de notificación')[['ID de caso', 'Ciudad de ubicación',
       'Departamento o Distrito ', 'Acumulados', 'Día número',
       'Penetración real']].max()

In [30]:
gompertz_Colombia

,ID de caso,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
Fecha de notificación,,,,,,
2020-03-02,1,NaN,NaN,1,0,0
2020-03-03,0,NaN,NaN,1,0,0
2020-03-04,0,NaN,NaN,1,0,0
2020-03-05,0,NaN,NaN,1,0,0
2020-03-06,1,NaN,NaN,2,0,0
2020-03-07,1,NaN,NaN,3,0,0
2020-03-08,1,NaN,NaN,5,0,0
2020-03-09,1,NaN,NaN,8,0,0
2020-03-10,1,NaN,NaN,12,0,0
2020-03-11,1,NaN,NaN,20,0,0
2020-03-12,1,NaN,NaN,31,0,0
2020-03-13,1,NaN,NaN,44,0,0
2020-03-14,1,NaN,NaN,64,0,0
2020-03-15,1,NaN,NaN,83,0,0
2020-03-16,1,NaN,NaN,112,0,0
2020-03-17,1,NaN,NaN,154,0,0
2020-03-18,1,NaN,NaN,198,0,0
2020-03-19,1,NaN,NaN,267,0,0
2020-03-20,1,NaN,NaN,345,0,0
2020-03-21,1,NaN,NaN,425,0,0
2020-03-22,1,NaN,NaN,507,0,0
2020-03-23,1,NaN,NaN,601,0,0
2020-03-24,1,NaN,NaN,742,0,0
2020-03-25,1,NaN,NaN,905,0,0
2020-03-26,1,NaN,NaN,1064,0,0
2020-03-27,1,NaN,NaN,1224,0,0
2020-03-28,1,NaN,NaN,1390,0,0
2020-03-29,1,NaN,NaN,1528,0,0
2020-03-30,1,NaN,NaN,1722,0,0
2020-03-31,1,NaN,NaN,1912,0,0
2020-04-01,1,NaN,NaN,2107,0,0
2020-04-02,1,NaN,NaN,2273,0,0
2020-04-03,1,NaN,NaN,2460,0,0
2020-04-04,1,NaN,NaN,2620,0,0
2020-04-05,1,NaN,NaN,2721,0,0
2020-04-06,1,NaN,NaN,2871,0,0
2020-04-07,1,NaN,NaN,3028,0,0
2020-04-08,1,NaN,NaN,3154,0,0
2020-04-09,1,NaN,NaN,3296,0,0
2020-04-10,1,NaN,NaN,3417,0,0
2020-04-11,1,NaN,NaN,3665,0,0
2020-04-12,1,NaN,NaN,3822,0,0
2020-04-13,1,NaN,NaN,4008,0,0
2020-04-14,1,NaN,NaN,4246,0,0
2020-04-15,1,NaN,NaN,4415,0,0
2020-04-16,1,NaN,NaN,4672,0,0
2020-04-17,1,NaN,NaN,4851,0,0
2020-04-18,1,NaN,NaN,5057,0,0
2020-04-19,1,NaN,NaN,5278,0,0
2020-04-20,1,NaN,NaN,5495,0,0
2020-04-21,1,NaN,NaN,5716,0,0
2020-04-22,1,NaN,NaN,5964,0,0
2020-04-23,1,NaN,NaN,6266,0,0
2020-04-24,1,NaN,NaN,6572,0,0
2020-04-25,1,NaN,NaN,6878,0,0
2020-04-26,1,NaN,NaN,7130,0,0
2020-04-27,1,NaN,NaN,7538,0,0
2020-04-28,1,NaN,NaN,8054,0,0
2020-04-29,1,NaN,NaN,8432,0,0
2020-04-30,1,NaN,NaN,8907,0,0
2020-05-01,1,NaN,NaN,9373,0,0
2020-05-02,1,NaN,NaN,9837,0,0
2020-05-03,1,NaN,NaN,10229,0,0
2020-05-04,1,NaN,NaN,10739,0,0
2020-05-05,1,NaN,NaN,11527,0,0
2020-05-06,1,NaN,NaN,12274,0,0
2020-05-07,1,NaN,NaN,13045,0,0
2020-05-08,1,NaN,NaN,14024,0,0
2020-05-09,1,NaN,NaN,14767,0,0
2020-05-10,1,NaN,NaN,15239,0,0
2020-05-11,1,NaN,NaN,15971,0,0
2020-05-12,1,NaN,NaN,16793,0,0
2020-05-13,1,NaN,NaN,17640,0,0
2020-05-14,1,NaN,NaN,18699,0,0
2020-05-15,1,NaN,NaN,19674,0,0
2020-05-16,1,NaN,NaN,20579,0,0
2020-05-17,1,NaN,NaN,21421,0,0
2020-05-18,1,NaN,NaN,22621,0,0
2020-05-19,1,NaN,NaN,23782,0,0
2020-05-20,1,NaN,NaN,25177,0,0
2020-05-21,1,NaN,NaN,26540,0,0
2020-05-22,1,NaN,NaN,27951,0,0
2020-05-23,1,NaN,NaN,29372,0,0
2020-05-24,1,NaN,NaN,30279,0,0
2020-05-25,1,NaN,NaN,31436,0,0
2020-05-26,1,NaN,NaN,32954,0,0
2020-05-27,1,NaN,NaN,34320,0,0
2020-05-28,1,NaN,NaN,35728,0,0
2020-05-29,1,NaN,NaN,37137,0,0
2020-05-30,1,NaN,NaN,38436,0,0
2020-05-31,1,NaN,NaN,39475,0,0
2020-06-01,1,NaN,NaN,41216,0,0
2020-06-02,1,NaN,NaN,42862,0,0
2020-06-03,1,NaN,NaN,44753,0,0
2020-06-04,1,NaN,NaN,46527,0,0
2020-06-05,1,NaN,NaN,48539,0,0
2020-06-06,1,NaN,NaN,50336,0,0
2020-06-07,1,NaN,NaN,51803,0,0
2020-06-08,1,NaN,NaN,54338,0,0
2020-06-09,1,NaN,NaN,56760,0,0
2020-06-10,1,NaN,NaN,59550,0,0
2020-06-11,1,NaN,NaN,62500,0,0
2020-06-12,1,NaN,NaN,65452,0,0
2020-06-13,1,NaN,NaN,67914,0,0
2020-06-14,1,NaN,NaN,69566,0,0
2020-06-15,1,NaN,NaN,71452,0,0
2020-06-16,1,NaN,NaN,75177,0,0
2020-06-17,1,NaN,NaN,79158,0,0
2020-06-18,1,NaN,NaN,83040,0,0
2020-06-19,1,NaN,NaN,87034,0,0
2020-06-20,1,NaN,NaN,90507,0,0
2020-06-21,1,NaN,NaN,93112,0,0
2020-06-22,1,NaN,NaN,96047,0,0
2020-06-23,1,NaN,NaN,101081,0,0
2020-06-24,1,NaN,NaN,106138,0,0
2020-06-25,1,NaN,NaN,111297,0,0
2020-06-26,1,NaN,NaN,116876,0,0
2020-06-27,1,NaN,NaN,121522,0,0
2020-06-28,1,NaN,NaN,125077,0,0
2020-06-29,1,NaN,NaN,128881,0,0
2020-06-30,1,NaN,NaN,134869,0,0
2020-07-01,1,NaN,NaN,141081,0,0
2020-07-02,1,NaN,NaN,147286,0,0
2020-07-03,1,NaN,NaN,154056,0,0
2020-07-04,1,NaN,NaN,160284,0,0
2020-07-05,1,NaN,NaN,164819,0,0
2020-07-06,1,NaN,NaN,172054,0,0
2020-07-07,1,NaN,NaN,179003,0,0
2020-07-08,1,NaN,NaN,186734,0,0
2020-07-09,1,NaN,NaN,193592,0,0
2020-07-10,1,NaN,NaN,201362,0,0
2020-07-11,1,NaN,NaN,207620,0,0
2020-07-12,1,NaN,NaN,212489,0,0
2020-07-13,1,NaN,NaN,221333,0,0
2020-07-14,1,NaN,NaN,229794,0,0
2020-07-15,1,NaN,NaN,237965,0,0
2020-07-16,1,NaN,NaN,246538,0,0
2020-07-17,1,NaN,NaN,255205,0,0
2020-07-18,1,NaN,NaN,263677,0,0
2020-07-19,1,NaN,NaN,269196,0,0
2020-07-20,1,NaN,NaN,275270,0,0
2020-07-21,1,NaN,NaN,283953,0,0
2020-07-22,1,NaN,NaN,291622,0,0
2020-07-23,1,NaN,NaN,298503,0,0
2020-07-24,1,NaN,NaN,305304,0,0
2020-07-25,1,NaN,NaN,310220,0,0
2020-07-26,1,NaN,NaN,313349,0,0
2020-07-27,1,NaN,NaN,319012,0,0
2020-07-28,1,NaN,NaN,323648,0,0
2020-07-29,1,NaN,NaN,327502,0,0
2020-07-30,1,NaN,NaN,330722,0,0
2020-07-31,1,NaN,NaN,332941,0,0
2020-08-01,1,NaN,NaN,334191,0,0
2020-08-02,1,NaN,NaN,334596,0,0
2020-08-03,1,NaN,NaN,334962,0,0
2020-08-04,1,Valle de San José,Santander,334979,0,0

In [31]:
gompertz_Colombia.reset_index(inplace=True)

In [32]:
longitud = gompertz_Colombia['ID de caso'].size
longitud

156

In [33]:
gompertz_Colombia.columns

Index(['Fecha de notificación', 'ID de caso', 'Ciudad de ubicación',
       'Departamento o Distrito ', 'Acumulados', 'Día número',
       'Penetración real'],
      dtype='object')

In [34]:
gompertz_Colombia.loc[0, 'Día número'] = 1
for i in range(1, longitud):
    gompertz_Colombia.loc[i,'Día número'] = i+1
    gompertz_Colombia.loc[i,'Penetración real'] = gompertz_Colombia.loc[i, 'Acumulados']/ gompertz_Colombia.loc[longitud-1, 'Acumulados']

In [35]:
gompertz_Colombia

,Fecha de notificación,ID de caso,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,2020-03-02,1,NaN,NaN,1,1,0.000000
1,2020-03-03,0,NaN,NaN,1,2,0.000003
2,2020-03-04,0,NaN,NaN,1,3,0.000003
3,2020-03-05,0,NaN,NaN,1,4,0.000003
4,2020-03-06,1,NaN,NaN,2,5,0.000006
5,2020-03-07,1,NaN,NaN,3,6,0.000009
6,2020-03-08,1,NaN,NaN,5,7,0.000015
7,2020-03-09,1,NaN,NaN,8,8,0.000024
8,2020-03-10,1,NaN,NaN,12,9,0.000036
9,2020-03-11,1,NaN,NaN,20,10,0.000060
10,2020-03-12,1,NaN,NaN,31,11,0.000093
11,2020-03-13,1,NaN,NaN,44,12,0.000131
12,2020-03-14,1,NaN,NaN,64,13,0.000191
13,2020-03-15,1,NaN,NaN,83,14,0.000248
14,2020-03-16,1,NaN,NaN,112,15,0.000334
15,2020-03-17,1,NaN,NaN,154,16,0.000460
16,2020-03-18,1,NaN,NaN,198,17,0.000591
17,2020-03-19,1,NaN,NaN,267,18,0.000797
18,2020-03-20,1,NaN,NaN,345,19,0.001030
19,2020-03-21,1,NaN,NaN,425,20,0.001269
20,2020-03-22,1,NaN,NaN,507,21,0.001514
21,2020-03-23,1,NaN,NaN,601,22,0.001794
22,2020-03-24,1,NaN,NaN,742,23,0.002215
23,2020-03-25,1,NaN,NaN,905,24,0.002702
24,2020-03-26,1,NaN,NaN,1064,25,0.003176
25,2020-03-27,1,NaN,NaN,1224,26,0.003654
26,2020-03-28,1,NaN,NaN,1390,27,0.004150
27,2020-03-29,1,NaN,NaN,1528,28,0.004561
28,2020-03-30,1,NaN,NaN,1722,29,0.005141
29,2020-03-31,1,NaN,NaN,1912,30,0.005708
30,2020-04-01,1,NaN,NaN,2107,31,0.006290
31,2020-04-02,1,NaN,NaN,2273,32,0.006785
32,2020-04-03,1,NaN,NaN,2460,33,0.007344
33,2020-04-04,1,NaN,NaN,2620,34,0.007821
34,2020-04-05,1,NaN,NaN,2721,35,0.008123
35,2020-04-06,1,NaN,NaN,2871,36,0.008571
36,2020-04-07,1,NaN,NaN,3028,37,0.009039
37,2020-04-08,1,NaN,NaN,3154,38,0.009416
38,2020-04-09,1,NaN,NaN,3296,39,0.009839
39,2020-04-10,1,NaN,NaN,3417,40,0.010201
40,2020-04-11,1,NaN,NaN,3665,41,0.010941
41,2020-04-12,1,NaN,NaN,3822,42,0.011410
42,2020-04-13,1,NaN,NaN,4008,43,0.011965
43,2020-04-14,1,NaN,NaN,4246,44,0.012675
44,2020-04-15,1,NaN,NaN,4415,45,0.013180
45,2020-04-16,1,NaN,NaN,4672,46,0.013947
46,2020-04-17,1,NaN,NaN,4851,47,0.014482
47,2020-04-18,1,NaN,NaN,5057,48,0.015096
48,2020-04-19,1,NaN,NaN,5278,49,0.015756
49,2020-04-20,1,NaN,NaN,5495,50,0.016404
50,2020-04-21,1,NaN,NaN,5716,51,0.017064
51,2020-04-22,1,NaN,NaN,5964,52,0.017804
52,2020-04-23,1,NaN,NaN,6266,53,0.018706
53,2020-04-24,1,NaN,NaN,6572,54,0.019619
54,2020-04-25,1,NaN,NaN,6878,55,0.020533
55,2020-04-26,1,NaN,NaN,7130,56,0.021285
56,2020-04-27,1,NaN,NaN,7538,57,0.022503
57,2020-04-28,1,NaN,NaN,8054,58,0.024043
58,2020-04-29,1,NaN,NaN,8432,59,0.025172
59,2020-04-30,1,NaN,NaN,8907,60,0.026590
60,2020-05-01,1,NaN,NaN,9373,61,0.027981
61,2020-05-02,1,NaN,NaN,9837,62,0.029366
62,2020-05-03,1,NaN,NaN,10229,63,0.030536
63,2020-05-04,1,NaN,NaN,10739,64,0.032059
64,2020-05-05,1,NaN,NaN,11527,65,0.034411
65,2020-05-06,1,NaN,NaN,12274,66,0.036641
66,2020-05-07,1,NaN,NaN,13045,67,0.038943
67,2020-05-08,1,NaN,NaN,14024,68,0.041865
68,2020-05-09,1,NaN,NaN,14767,69,0.044083
69,2020-05-10,1,NaN,NaN,15239,70,0.045492
70,2020-05-11,1,NaN,NaN,15971,71,0.047678
71,2020-05-12,1,NaN,NaN,16793,72,0.050132
72,2020-05-13,1,NaN,NaN,17640,73,0.052660
73,2020-05-14,1,NaN,NaN,18699,74,0.055821
74,2020-05-15,1,NaN,NaN,19674,75,0.058732
75,2020-05-16,1,NaN,NaN,20579,76,0.061434
76,2020-05-17,1,NaN,NaN,21421,77,0.063947
77,2020-05-18,1,NaN,NaN,22621,78,0.067530
78,2020-05-19,1,NaN,NaN,23782,79,0.070995
79,2020-05-20,1,NaN,NaN,25177,80,0.075160
80,2020-05-21,1,NaN,NaN,26540,81,0.079229
81,2020-05-22,1,NaN,NaN,27951,82,0.083441
82,2020-05-23,1,NaN,NaN,29372,83,0.087683
83,2020-05-24,1,NaN,NaN,30279,84,0.090391
84,2020-05-25,1,NaN,NaN,31436,85,0.093845
85,2020-05-26,1,NaN,NaN,32954,86,0.098376
86,2020-05-27,1,NaN,NaN,34320,87,0.102454
87,2020-05-28,1,NaN,NaN,35728,88,0.106657
88,2020-05-29,1,NaN,NaN,37137,89,0.110864
89,2020-05-30,1,NaN,NaN,38436,90,0.114742
90,2020-05-31,1,NaN,NaN,39475,91,0.117843
91,2020-06-01,1,NaN,NaN,41216,92,0.123041
92,2020-06-02,1,NaN,NaN,42862,93,0.127954
93,2020-06-03,1,NaN,NaN,44753,94,0.133599
94,2020-06-04,1,NaN,NaN,46527,95,0.138895
95,2020-06-05,1,NaN,NaN,48539,96,0.144902
96,2020-06-06,1,NaN,NaN,50336,97,0.150266
97,2020-06-07,1,NaN,NaN,51803,98,0.154646
98,2020-06-08,1,NaN,NaN,54338,99,0.162213
99,2020-06-09,1,NaN,NaN,56760,100,0.169443
100,2020-06-10,1,NaN,NaN,59550,101,0.177772
101,2020-06-11,1,NaN,NaN,62500,102,0.186579
102,2020-06-12,1,NaN,NaN,65452,103,0.195391
103,2020-06-13,1,NaN,NaN,67914,104,0.202741
104,2020-06-14,1,NaN,NaN,69566,105,0.207673
105,2020-06-15,1,NaN,NaN,71452,106,0.213303
106,2020-06-16,1,NaN,NaN,75177,107,0.224423
107,2020-06-17,1,NaN,NaN,79158,108,0.236307
108,2020-06-18,1,NaN,NaN,83040,109,0.247896
109,2020-06-19,1,NaN,NaN,87034,110,0.259819
110,2020-06-20,1,NaN,NaN,90507,111,0.270187
111,2020-06-21,1,NaN,NaN,93112,112,0.277964
112,2020-06-22,1,NaN,NaN,96047,113,0.286725
113,2020-06-23,1,NaN,NaN,101081,114,0.301753
114,2020-06-24,1,NaN,NaN,106138,115,0.316850
115,2020-06-25,1,NaN,NaN,111297,116,0.332251
116,2020-06-26,1,NaN,NaN,116876,117,0.348905
117,2020-06-27,1,NaN,NaN,121522,118,0.362775
118,2020-06-28,1,NaN,NaN,125077,119,0.373388
119,2020-06-29,1,NaN,NaN,128881,120,0.384744
120,2020-06-30,1,NaN,NaN,134869,121,0.402619
121,2020-07-01,1,NaN,NaN,141081,122,0.421164
122,2020-07-02,1,NaN,NaN,147286,123,0.439687
123,2020-07-03,1,NaN,NaN,154056,124,0.459897
124,2020-07-04,1,NaN,NaN,160284,125,0.478490
125,2020-07-05,1,NaN,NaN,164819,126,0.492028
126,2020-07-06,1,NaN,NaN,172054,127,0.513626
127,2020-07-07,1,NaN,NaN,179003,128,0.534371
128,2020-07-08,1,NaN,NaN,186734,129,0.557450
129,2020-07-09,1,NaN,NaN,193592,130,0.577923
130,2020-07-10,1,NaN,NaN,201362,131,0.601118
131,2020-07-11,1,NaN,NaN,207620,132,0.619800
132,2020-07-12,1,NaN,NaN,212489,133,0.634335
133,2020-07-13,1,NaN,NaN,221333,134,0.660737
134,2020-07-14,1,NaN,NaN,229794,135,0.685995
135,2020-07-15,1,NaN,NaN,237965,136,0.710388
136,2020-07-16,1,NaN,NaN,246538,137,0.735980
137,2020-07-17,1,NaN,NaN,255205,138,0.761854
138,2020-07-18,1,NaN,NaN,263677,139,0.787145
139,2020-07-19,1,NaN,NaN,269196,140,0.803621
140,2020-07-20,1,NaN,NaN,275270,141,0.821753
141,2020-07-21,1,NaN,NaN,283953,142,0.847674
142,2020-07-22,1,NaN,NaN,291622,143,0.870568
143,2020-07-23,1,NaN,NaN,298503,144,0.891110
144,2020-07-24,1,NaN,NaN,305304,145,0.911412
145,2020-07-25,1,NaN,NaN,310220,146,0.926088
146,2020-07-26,1,NaN,NaN,313349,147,0.935429
147,2020-07-27,1,NaN,NaN,319012,148,0.952334
148,2020-07-28,1,NaN,NaN,323648,149,0.966174
149,2020-07-29,1,NaN,NaN,327502,150,0.977679
150,2020-07-30,1,NaN,NaN,330722,151,0.987292
151,2020-07-31,1,NaN,NaN,332941,152,0.993916
152,2020-08-01,1,NaN,NaN,334191,153,0.997648
153,2020-08-02,1,NaN,NaN,334596,154,0.998857
154,2020-08-03,1,NaN,NaN,334962,155,0.999949
155,2020-08-04,1,Valle de San José,Santander,334979,156,1.000000

In [36]:

gompertz_Colombia.to_excel('GompertzCol.xlsx')