In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 500)

In [3]:
gompertz = pd.read_csv('CovidColombia.csv', low_memory=False, usecols= ['ID de caso', 'Fecha de notificación', 
                                                                        'Ciudad de ubicación', 
                                                                        'Departamento o Distrito '], 
                                                                        parse_dates=['Fecha de notificación'] )

In [4]:
gompertz.sort_values(by=['Fecha de notificación'],inplace=True)

In [5]:
gompertz

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,2,2020-03-06,Guadalajara de Buga,Valle del Cauca
2,3,2020-03-07,Medellín,Antioquia
6,7,2020-03-08,Cartagena de Indias,Cartagena D.T. y C.
8,9,2020-03-08,Bogotá D.C.,Bogotá D.C.
...,...,...,...,...
237399,237440,2020-07-25,Bucaramanga,Santander
236820,236861,2020-07-25,Manizales,Caldas
236818,236859,2020-07-25,Manizales,Caldas
237019,237060,2020-07-25,Cartagena de Indias,Cartagena D.T. y C.
237230,237271,2020-07-25,Bucaramanga,Santander

In [6]:
df = pd.DataFrame(gompertz['Fecha de notificación']).loc[0]
df

Fecha de notificación   2020-03-02
Name: 0, dtype: datetime64[ns]

In [7]:
a = gompertz.loc[0,'Fecha de notificación']

In [8]:
b = np.datetime64('today') 
b

numpy.datetime64('2020-07-27')

In [9]:
longitud = (b-a)/ np.timedelta64(1, 'D')
longitud=int(longitud)-1
longitud

146

In [10]:
df_fechas = pd.DataFrame(df).transpose()
df_fechas

  Fecha de notificación
0            2020-03-02

In [11]:
df_fechas['ID de caso']=0

In [12]:
df_fechas

  Fecha de notificación  ID de caso
0            2020-03-02           0

In [13]:
pd.to_datetime([df_fechas.loc[0,'Fecha de notificación']])

DatetimeIndex(['2020-03-02'], dtype='datetime64[ns]', freq=None)

In [14]:
(np.datetime64(df_fechas.loc[0, 'Fecha de notificación']) + np.timedelta64(1,'D'))

numpy.datetime64('2020-03-03T00:00:00.000000')

In [15]:
for i in range(1,longitud):
    df_fechas.loc[(i)] = [(np.datetime64(df_fechas.loc[i-1, 'Fecha de notificación']) + np.timedelta64(1,'D')),0]

In [16]:
df_fechas

    Fecha de notificación  ID de caso
0              2020-03-02           0
1              2020-03-03           0
2              2020-03-04           0
3              2020-03-05           0
4              2020-03-06           0
5              2020-03-07           0
6              2020-03-08           0
7              2020-03-09           0
8              2020-03-10           0
9              2020-03-11           0
10             2020-03-12           0
11             2020-03-13           0
12             2020-03-14           0
13             2020-03-15           0
14             2020-03-16           0
15             2020-03-17           0
16             2020-03-18           0
17             2020-03-19           0
18             2020-03-20           0
19             2020-03-21           0
20             2020-03-22           0
21             2020-03-23           0
22             2020-03-24           0
23             2020-03-25           0
24             2020-03-26           0
25             2020-03-27           0
26             2020-03-28           0
27             2020-03-29           0
28             2020-03-30           0
29             2020-03-31           0
30             2020-04-01           0
31             2020-04-02           0
32             2020-04-03           0
33             2020-04-04           0
34             2020-04-05           0
35             2020-04-06           0
36             2020-04-07           0
37             2020-04-08           0
38             2020-04-09           0
39             2020-04-10           0
40             2020-04-11           0
41             2020-04-12           0
42             2020-04-13           0
43             2020-04-14           0
44             2020-04-15           0
45             2020-04-16           0
46             2020-04-17           0
47             2020-04-18           0
48             2020-04-19           0
49             2020-04-20           0
50             2020-04-21           0
51             2020-04-22           0
52             2020-04-23           0
53             2020-04-24           0
54             2020-04-25           0
55             2020-04-26           0
56             2020-04-27           0
57             2020-04-28           0
58             2020-04-29           0
59             2020-04-30           0
60             2020-05-01           0
61             2020-05-02           0
62             2020-05-03           0
63             2020-05-04           0
64             2020-05-05           0
65             2020-05-06           0
66             2020-05-07           0
67             2020-05-08           0
68             2020-05-09           0
69             2020-05-10           0
70             2020-05-11           0
71             2020-05-12           0
72             2020-05-13           0
73             2020-05-14           0
74             2020-05-15           0
75             2020-05-16           0
76             2020-05-17           0
77             2020-05-18           0
78             2020-05-19           0
79             2020-05-20           0
80             2020-05-21           0
81             2020-05-22           0
82             2020-05-23           0
83             2020-05-24           0
84             2020-05-25           0
85             2020-05-26           0
86             2020-05-27           0
87             2020-05-28           0
88             2020-05-29           0
89             2020-05-30           0
90             2020-05-31           0
91             2020-06-01           0
92             2020-06-02           0
93             2020-06-03           0
94             2020-06-04           0
95             2020-06-05           0
96             2020-06-06           0
97             2020-06-07           0
98             2020-06-08           0
99             2020-06-09           0
100            2020-06-10           0
101            2020-06-11           0
102            2020-06-12           0
103            2020-06-13           0
104            2020-06-14           0
105            2020-06-15           0
106            2020-06-16           0
107            2020-06-17           0
108            2020-06-18           0
109            2020-06-19           0
110            2020-06-20           0
111            2020-06-21           0
112            2020-06-22           0
113            2020-06-23           0
114            2020-06-24           0
115            2020-06-25           0
116            2020-06-26           0
117            2020-06-27           0
118            2020-06-28           0
119            2020-06-29           0
120            2020-06-30           0
121            2020-07-01           0
122            2020-07-02           0
123            2020-07-03           0
124            2020-07-04           0
125            2020-07-05           0
126            2020-07-06           0
127            2020-07-07           0
128            2020-07-08           0
129            2020-07-09           0
130            2020-07-10           0
131            2020-07-11           0
132            2020-07-12           0
133            2020-07-13           0
134            2020-07-14           0
135            2020-07-15           0
136            2020-07-16           0
137            2020-07-17           0
138            2020-07-18           0
139            2020-07-19           0
140            2020-07-20           0
141            2020-07-21           0
142            2020-07-22           0
143            2020-07-23           0
144            2020-07-24           0
145            2020-07-25           0

In [17]:
gompertz_Col=gompertz.append(df_fechas).sort_values(by=['Fecha de notificación'], ignore_index=True)

In [18]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
240936,236583,2020-07-25,Calarcá,Quindío
240937,237440,2020-07-25,Bucaramanga,Santander
240938,236861,2020-07-25,Manizales,Caldas
240939,237271,2020-07-25,Bucaramanga,Santander
240940,0,2020-07-25,NaN,NaN

In [19]:
longitud = gompertz_Col['ID de caso'].size
longitud

240941

In [20]:
for i in range(0, longitud):
    if gompertz_Col.loc[i, 'ID de caso'] == 0:
        pass
    else:
        gompertz_Col.loc[i, 'ID de caso'] = 1

In [21]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
240936,1,2020-07-25,Calarcá,Quindío
240937,1,2020-07-25,Bucaramanga,Santander
240938,1,2020-07-25,Manizales,Caldas
240939,1,2020-07-25,Bucaramanga,Santander
240940,0,2020-07-25,NaN,NaN

In [22]:
gompertz_Col['Acumulados']= 0
gompertz_Col['Día número']=0
gompertz_Col['Penetración real']=0
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,0,0,0
1,0,2020-03-02,NaN,NaN,0,0,0
2,0,2020-03-03,NaN,NaN,0,0,0
3,0,2020-03-04,NaN,NaN,0,0,0
4,0,2020-03-05,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...
240936,1,2020-07-25,Calarcá,Quindío,0,0,0
240937,1,2020-07-25,Bucaramanga,Santander,0,0,0
240938,1,2020-07-25,Manizales,Caldas,0,0,0
240939,1,2020-07-25,Bucaramanga,Santander,0,0,0
240940,0,2020-07-25,NaN,NaN,0,0,0

In [23]:
gompertz_Col.loc[0, 'Acumulados']= gompertz_Col.loc[0, 'ID de caso']
for i in range(1, longitud):
    gompertz_Col.loc[i,'Acumulados'] = gompertz_Col.loc[i, 'ID de caso'] + gompertz_Col.loc[i-1, 'Acumulados']

In [24]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,1,0,0
1,0,2020-03-02,NaN,NaN,1,0,0
2,0,2020-03-03,NaN,NaN,1,0,0
3,0,2020-03-04,NaN,NaN,1,0,0
4,0,2020-03-05,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...
240936,1,2020-07-25,Calarcá,Quindío,240792,0,0
240937,1,2020-07-25,Bucaramanga,Santander,240793,0,0
240938,1,2020-07-25,Manizales,Caldas,240794,0,0
240939,1,2020-07-25,Bucaramanga,Santander,240795,0,0
240940,0,2020-07-25,NaN,NaN,240795,0,0

In [25]:
gompertz_Col = gompertz_Col.groupby('Fecha de notificación')[['ID de caso', 'Ciudad de ubicación',
       'Departamento o Distrito ', 'Acumulados', 'Día número',
       'Penetración real']].max()

In [26]:
gompertz_Col

,ID de caso,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
Fecha de notificación,,,,,,
2020-03-02 00:00:00,1,NaN,NaN,1,0,0
2020-03-03 00:00:00,0,NaN,NaN,1,0,0
2020-03-04 00:00:00,0,NaN,NaN,1,0,0
2020-03-05 00:00:00,0,NaN,NaN,1,0,0
2020-03-06 00:00:00,1,NaN,NaN,2,0,0
2020-03-07 00:00:00,1,NaN,NaN,3,0,0
2020-03-08 00:00:00,1,NaN,NaN,5,0,0
2020-03-09 00:00:00,1,NaN,NaN,8,0,0
2020-03-10 00:00:00,1,NaN,NaN,12,0,0
2020-03-11 00:00:00,1,NaN,NaN,20,0,0
2020-03-12 00:00:00,1,NaN,NaN,31,0,0
2020-03-13 00:00:00,1,NaN,NaN,44,0,0
2020-03-14 00:00:00,1,NaN,NaN,64,0,0
2020-03-15 00:00:00,1,NaN,NaN,83,0,0
2020-03-16 00:00:00,1,NaN,NaN,112,0,0
2020-03-17 00:00:00,1,NaN,NaN,154,0,0
2020-03-18 00:00:00,1,NaN,NaN,198,0,0
2020-03-19 00:00:00,1,NaN,NaN,267,0,0
2020-03-20 00:00:00,1,NaN,NaN,345,0,0
2020-03-21 00:00:00,1,NaN,NaN,425,0,0
2020-03-22 00:00:00,1,NaN,NaN,507,0,0
2020-03-23 00:00:00,1,NaN,NaN,601,0,0
2020-03-24 00:00:00,1,NaN,NaN,742,0,0
2020-03-25 00:00:00,1,NaN,NaN,905,0,0
2020-03-26 00:00:00,1,NaN,NaN,1064,0,0
2020-03-27 00:00:00,1,NaN,NaN,1224,0,0
2020-03-28 00:00:00,1,NaN,NaN,1390,0,0
2020-03-29 00:00:00,1,NaN,NaN,1528,0,0
2020-03-30 00:00:00,1,NaN,NaN,1722,0,0
2020-03-31 00:00:00,1,NaN,NaN,1912,0,0
2020-04-01 00:00:00,1,NaN,NaN,2107,0,0
2020-04-02 00:00:00,1,NaN,NaN,2273,0,0
2020-04-03 00:00:00,1,NaN,NaN,2460,0,0
2020-04-04 00:00:00,1,NaN,NaN,2620,0,0
2020-04-05 00:00:00,1,NaN,NaN,2721,0,0
2020-04-06 00:00:00,1,NaN,NaN,2871,0,0
2020-04-07 00:00:00,1,NaN,NaN,3028,0,0
2020-04-08 00:00:00,1,NaN,NaN,3154,0,0
2020-04-09 00:00:00,1,NaN,NaN,3295,0,0
2020-04-10 00:00:00,1,NaN,NaN,3416,0,0
2020-04-11 00:00:00,1,NaN,NaN,3664,0,0
2020-04-12 00:00:00,1,NaN,NaN,3821,0,0
2020-04-13 00:00:00,1,NaN,NaN,4007,0,0
2020-04-14 00:00:00,1,NaN,NaN,4245,0,0
2020-04-15 00:00:00,1,NaN,NaN,4414,0,0
2020-04-16 00:00:00,1,NaN,NaN,4671,0,0
2020-04-17 00:00:00,1,NaN,NaN,4850,0,0
2020-04-18 00:00:00,1,NaN,NaN,5056,0,0
2020-04-19 00:00:00,1,NaN,NaN,5277,0,0
2020-04-20 00:00:00,1,NaN,NaN,5494,0,0
2020-04-21 00:00:00,1,NaN,NaN,5715,0,0
2020-04-22 00:00:00,1,NaN,NaN,5963,0,0
2020-04-23 00:00:00,1,NaN,NaN,6265,0,0
2020-04-24 00:00:00,1,NaN,NaN,6571,0,0
2020-04-25 00:00:00,1,NaN,NaN,6877,0,0
2020-04-26 00:00:00,1,NaN,NaN,7129,0,0
2020-04-27 00:00:00,1,NaN,NaN,7537,0,0
2020-04-28 00:00:00,1,NaN,NaN,8053,0,0
2020-04-29 00:00:00,1,NaN,NaN,8431,0,0
2020-04-30 00:00:00,1,NaN,NaN,8906,0,0
2020-05-01 00:00:00,1,NaN,NaN,9371,0,0
2020-05-02 00:00:00,1,NaN,NaN,9835,0,0
2020-05-03 00:00:00,1,NaN,NaN,10227,0,0
2020-05-04 00:00:00,1,NaN,NaN,10737,0,0
2020-05-05 00:00:00,1,NaN,NaN,11525,0,0
2020-05-06 00:00:00,1,NaN,NaN,12271,0,0
2020-05-07 00:00:00,1,NaN,NaN,13041,0,0
2020-05-08 00:00:00,1,NaN,NaN,14020,0,0
2020-05-09 00:00:00,1,NaN,NaN,14763,0,0
2020-05-10 00:00:00,1,NaN,NaN,15235,0,0
2020-05-11 00:00:00,1,NaN,NaN,15966,0,0
2020-05-12 00:00:00,1,NaN,NaN,16787,0,0
2020-05-13 00:00:00,1,NaN,NaN,17634,0,0
2020-05-14 00:00:00,1,NaN,NaN,18693,0,0
2020-05-15 00:00:00,1,NaN,NaN,19668,0,0
2020-05-16 00:00:00,1,NaN,NaN,20573,0,0
2020-05-17 00:00:00,1,NaN,NaN,21415,0,0
2020-05-18 00:00:00,1,NaN,NaN,22615,0,0
2020-05-19 00:00:00,1,NaN,NaN,23776,0,0
2020-05-20 00:00:00,1,NaN,NaN,25171,0,0
2020-05-21 00:00:00,1,NaN,NaN,26533,0,0
2020-05-22 00:00:00,1,NaN,NaN,27944,0,0
2020-05-23 00:00:00,1,NaN,NaN,29365,0,0
2020-05-24 00:00:00,1,NaN,NaN,30272,0,0
2020-05-25 00:00:00,1,NaN,NaN,31429,0,0
2020-05-26 00:00:00,1,NaN,NaN,32948,0,0
2020-05-27 00:00:00,1,NaN,NaN,34317,0,0
2020-05-28 00:00:00,1,NaN,NaN,35726,0,0
2020-05-29 00:00:00,1,NaN,NaN,37135,0,0
2020-05-30 00:00:00,1,NaN,NaN,38434,0,0
2020-05-31 00:00:00,1,NaN,NaN,39473,0,0
2020-06-01 00:00:00,1,NaN,NaN,41213,0,0
2020-06-02 00:00:00,1,NaN,NaN,42858,0,0
2020-06-03 00:00:00,1,NaN,NaN,44749,0,0
2020-06-04 00:00:00,1,NaN,NaN,46523,0,0
2020-06-05 00:00:00,1,NaN,NaN,48535,0,0
2020-06-06 00:00:00,1,NaN,NaN,50329,0,0
2020-06-07 00:00:00,1,NaN,NaN,51796,0,0
2020-06-08 00:00:00,1,NaN,NaN,54331,0,0
2020-06-09 00:00:00,1,NaN,NaN,56749,0,0
2020-06-10 00:00:00,1,NaN,NaN,59536,0,0
2020-06-11 00:00:00,1,NaN,NaN,62483,0,0
2020-06-12 00:00:00,1,NaN,NaN,65431,0,0
2020-06-13 00:00:00,1,NaN,NaN,67892,0,0
2020-06-14 00:00:00,1,NaN,NaN,69540,0,0
2020-06-15 00:00:00,1,NaN,NaN,71426,0,0
2020-06-16 00:00:00,1,NaN,NaN,75147,0,0
2020-06-17 00:00:00,1,NaN,NaN,79121,0,0
2020-06-18 00:00:00,1,NaN,NaN,83002,0,0
2020-06-19 00:00:00,1,NaN,NaN,86981,0,0
2020-06-20 00:00:00,1,NaN,NaN,90432,0,0
2020-06-21 00:00:00,1,NaN,NaN,93035,0,0
2020-06-22 00:00:00,1,NaN,NaN,95965,0,0
2020-06-23 00:00:00,1,NaN,NaN,100990,0,0
2020-06-24 00:00:00,1,NaN,NaN,106034,0,0
2020-06-25 00:00:00,1,NaN,NaN,111183,0,0
2020-06-25 11:59:44,1,Barranquilla,Barranquilla D.E.,111184,0,0
2020-06-26 00:00:00,1,NaN,NaN,116660,0,0
2020-06-27 00:00:00,1,NaN,NaN,121139,0,0
2020-06-27 11:59:44,1,Sahagún,Córdoba,121140,0,0
2020-06-28 00:00:00,1,NaN,NaN,124684,0,0
2020-06-28 11:59:44,1,Soledad,Córdoba,124687,0,0
2020-06-29 00:00:00,1,NaN,NaN,128470,0,0
2020-06-29 11:59:44,1,Villavicencio,Meta,128471,0,0
2020-06-30 00:00:00,1,NaN,NaN,134372,0,0
2020-07-01 00:00:00,1,NaN,NaN,140511,0,0
2020-07-01 11:59:44,1,Sincelejo,Sucre,140513,0,0
2020-07-02 00:00:00,1,NaN,NaN,146561,0,0
2020-07-02 11:59:44,1,Barranquilla,Barranquilla D.E.,146562,0,0
2020-07-03 00:00:00,1,NaN,NaN,153189,0,0
2020-07-03 11:59:44,1,San Andrés de Tumaco,Nariño,153194,0,0
2020-07-04 00:00:00,1,NaN,NaN,159222,0,0
2020-07-04 11:59:44,1,Uribia,Nariño,159234,0,0
2020-07-05 00:00:00,1,NaN,NaN,163516,0,0
2020-07-05 11:59:44,1,Valencia,Santander,163526,0,0
2020-07-06 00:00:00,1,NaN,NaN,170131,0,0
2020-07-06 11:59:44,1,Zipaquirá,Santa Marta D.T. y C.,170138,0,0
2020-07-07 00:00:00,1,NaN,NaN,176462,0,0
2020-07-07 11:59:44,1,Turbaco,Valle del Cauca,176471,0,0
2020-07-08 00:00:00,1,NaN,NaN,183394,0,0
2020-07-08 11:59:44,1,Tauramena,Córdoba,183401,0,0
2020-07-09 00:00:00,1,NaN,NaN,189204,0,0
2020-07-09 11:59:44,1,Soledad,Sucre,189220,0,0
2020-07-10 00:00:00,1,NaN,NaN,195660,0,0
2020-07-10 11:59:44,1,Turbo,Valle del Cauca,195683,0,0
2020-07-11 00:00:00,1,NaN,NaN,200156,0,0
2020-07-11 11:59:44,1,Soledad,Valle del Cauca,200247,0,0
2020-07-12 00:00:00,1,NaN,NaN,203469,0,0
2020-07-12 11:59:44,1,Soledad,Sucre,203478,0,0
2020-07-13 00:00:00,1,NaN,NaN,209190,0,0
2020-07-14 00:00:00,1,NaN,NaN,214849,0,0
2020-07-15 00:00:00,1,NaN,NaN,220115,0,0
2020-07-16 00:00:00,1,NaN,NaN,224696,0,0
2020-07-17 00:00:00,1,NaN,NaN,228830,0,0
2020-07-18 00:00:00,1,NaN,NaN,231533,0,0
2020-07-19 00:00:00,1,NaN,NaN,233542,0,0
2020-07-20 00:00:00,1,NaN,NaN,235408,0,0
2020-07-21 00:00:00,1,NaN,NaN,237816,0,0
2020-07-21 11:59:44,1,Santa Marta,Santa Marta D.T. y C.,237818,0,0
2020-07-22 00:00:00,1,NaN,NaN,239648,0,0
2020-07-23 00:00:00,1,NaN,NaN,240345,0,0
2020-07-23 11:59:44,1,Valledupar,Valle del Cauca,240367,0,0
2020-07-24 00:00:00,1,NaN,NaN,240777,0,0
2020-07-25 00:00:00,1,NaN,NaN,240795,0,0

In [27]:
gompertz_Col.reset_index(inplace=True)

In [28]:
longitud = gompertz_Col['ID de caso'].size
longitud

164

In [ ]:
gompertz_Col.loc[0, 'Día número'] = 1
for i in range(1, longitud):
    gompertz_Col.loc[i,'Día número'] = i+1
    gompertz_Col.loc[i,'Penetración real'] = gompertz_Col.loc[i, 'Acumulados']/ gompertz_Col.loc[longitud-1, 'Acumulados']

In [ ]:
gompertz_Col

In [ ]:

gompertz_Col.to_excel('datosTotalesparaGompertzCol.xlsx')